- link:
    ~/.aliases: zsh/aliases
    ~/.antidote_plugins: zsh/antidote-plugins
    ~/.zshenv: zsh/zshenv
    ~/.zshrc: zsh/zshrc
    ~/.oh-my-zsh-custom: zsh/custom

- shell:
    - [touch ~/.customenv]
# vim: sw=2 ts=2 et
